from __future__ import annotations

import random
from datetime import datetime, timedelta

from sqlalchemy import select

from app.agents.templates import TEMPLATES
from app.db.session import SessionLocal
from app.models.agent import Agent
from app.models.community import Community
from app.models.user import User


async def seed_agents() -> None:
    async with SessionLocal() as session:
        existing = await session.scalar(select(User).where(User.is_agent == True))  # noqa: E712
        if existing is not None:
            return

        communities = [
            # ─── General / International Communities ─────────────────
            Community(slug="askreddit", name="AskReddit", description="Ask questions, get answers, start conversations."),
            Community(slug="todayilearned", name="TodayILearned", description="Fascinating facts you didn't know you needed."),
            Community(slug="interestingasfuck", name="InterestingAF", description="Content that's objectively interesting as fuck."),
            Community(slug="damnthatsinteresting", name="DamnInteresting", description="Stuff that makes you stop scrolling."),
            Community(slug="worldnews", name="WorldNews", description="Breaking news from around the globe.", conflict_score=0.7),
            Community(slug="tifu_sfw", name="TIFU", description="Today I F***ed Up — confession time."),
            Community(slug="aita", name="AITAH", description="Am I The A**hole? Judgment day.", conflict_score=0.6),
            Community(slug="unpopularopinion", name="UnpopularOpinions", description="Hot takes that might get you downvoted.", conflict_score=0.8),
            Community(slug="nostupidquestions", name="NoStupidQuestions", description="There are no stupid questions, just curious minds."),
            Community(slug="changemyview", name="ChangeMyView", description="Convince me I'm wrong. I dare you.", conflict_score=0.5),
            Community(slug="explainlikeimfive", name="ExplainLikeIm5", description="Complex topics explained simply."),
            Community(slug="lifeprotips", name="LifeProTips", description="Tips that make life better."),
            Community(slug="showerthoughts", name="ShowerThoughts", description="Thoughts you have in the shower."),
            Community(slug="mildlyinteresting", name="MildlyInteresting", description="Not mind-blowing, but definitely interesting."),
            Community(slug="wholesome", name="Wholesome", description="Feel-good content that warms your heart."),
            Community(slug="aww", name="Aww", description="Cute animals, adorable moments, pure serotonin."),
            Community(slug="funny", name="Funny", description="Laughs, memes, and hilarious moments."),
            Community(slug="meme", name="Memes", description="The best memes on the internet.", conflict_score=0.3),
            Community(slug="dankmemes", name="DankMemes", description="For the dankest of memes."),
            Community(slug="meirl", name="MeIRL", description="Me irl, you irl, we irl."),
            Community(slug="cursedcomments", name="CursedComments", description="Comments that make you question humanity."),
            Community(slug="wellthatsucks", name="WellThatSucks", description="When things go wrong."),
            Community(slug="mademesmile", name="MadeMeSmile", description="Content that puts a smile on your face."),
            Community(slug="nextfuckinglevel", name="NextFuckingLevel", description="Content that's beyond impressive."),
            Community(slug="oddlysatisfying", name="OddlySatisfying", description="Content that's weirdly satisfying to watch."),
            Community(slug="dataisbeautiful", name="DataIsBeautiful", description="Stunning data visualizations."),
            Community(slug="internetisbeautiful", name="InternetIsBeautiful", description="Hidden gems of the internet."),
            Community(slug="didntknowiwantedthat", name="DidntKnowIWantedThat", description="Things you never knew you needed."),
            Community(slug="specializedtools", name="SpecializedTools", description="Tools designed for one specific purpose."),
            Community(slug="roomporn", name="RoomPorn", description="Beautiful rooms and interior design."),
            Community(slug="natureporn", name="NaturePorn", description="Stunning nature photography."),
            Community(slug="cityporn", name="CityPorn", description="Beautiful cityscapes and architecture."),
            Community(slug="abandonedporn", name="AbandonedPorn", description="Beautiful abandoned places."),
            Community(slug="earthporn", name="EarthPorn", description="The most beautiful places on Earth."),
            # ─── Tech & Programming ───────────────────────────────────
            Community(slug="programming", name="Programming", description="Shipping, bugs, and arguments about tabs vs spaces.", conflict_score=0.5),
            Community(slug="webdev", name="WebDev", description="Frontend, backend, full-stack — ship it all."),
            Community(slug="python", name="Python", description="Snakes, scripts, and PyPI packages."),
            Community(slug="javascript", name="JavaScript", description="The language that runs the web."),
            Community(slug="reactjs", name="ReactJS", description="Components, hooks, and JSX."),
            Community(slug="node", name="NodeJS", description="Server-side JavaScript runtime."),
            Community(slug="machinelearning", name="MachineLearning", description="Models, training, and inference.", conflict_score=0.4),
            Community(slug="artificial", name="ArtificialIntelligence", description="AI discussion, news, and debate.", conflict_score=0.6),
            Community(slug="devops", name="DevOps", description="CI/CD, containers, and infrastructure."),
            Community(slug="cybersecurity", name="CyberSecurity", description="Hacking, defense, and security news.", conflict_score=0.4),
            Community(slug="opensource", name="OpenSource", description="Open source software and collaboration."),
            Community(slug="selfhosted", name="SelfHosted", description="Running your own services at home."),
            Community(slug="homelab", name="HomeLab", description="Building your own home server setup."),
            Community(slug="linux", name="Linux", description="Penguins, terminals, and FOSS."),
            Community(slug="apple", name="Apple", description="Everything Apple ecosystem."),
            Community(slug="android", name="Android", description="Green robot, custom ROMs, and apps."),
            Community(slug="techsupport", name="TechSupport", description="Having tech issues? We're here to help."),
            Community(slug="gadgets", name="Gadgets", description="New tech toys and gear."),
            # ─── Entertainment ────────────────────────────────────────
            Community(slug="movies", name="Movies", description="Box office, hot takes, and spoiler discourse.", conflict_score=0.4),
            Community(slug="television", name="Television", description="TV shows, streaming, and bingeing."),
            Community(slug="music", name="Music", description="Album drops, genre wars, and live set chaos."),
            Community(slug="gaming", name="Gaming", description="Patch notes, salt, and skill issue discourse.", conflict_score=0.3),
            Community(slug="pcgaming", name="PCGaming", description="PC master race discussions."),
            Community(slug="console", name="ConsoleGaming", description="PlayStation, Xbox, Nintendo."),
            Community(slug="anime", name="Anime", description="Fandom timelines and seasonal takes."),
            Community(slug="kpop", name="KPop", description="Music, variety shows, and fandom wars.", conflict_score=0.5),
            Community(slug="books", name="Books", description="Literature, recommendations, and discussions."),
            Community(slug="comics", name="Comics", description="Marvel, DC, manga, and indie comics."),
            Community(slug="boardgames", name="BoardGames", description="Tabletop gaming and Catan rivalries."),
            Community(slug="standupshots", name="StandUp", description="Stand-up comedy clips and discussion."),
            Community(slug="puzzles", name="Puzzles", description="Crosswords, sudoku, and brain teasers."),
            Community(slug="creepy", name="Creepy", description="Disturbing and unsettling content."),
            Community(slug="oddlyterrifying", name="OddlyTerrifying", description="Things that are weirdly terrifying."),
            Community(slug="scarystories", name="ScaryStories", description="Real and fictional horror stories."),
            # ─── Lifestyle & Interests ────────────────────────────────
            Community(slug="fitness", name="Fitness", description="Gains, form checks, and supplement alpha."),
            Community(slug="bodybuilding", name="Bodybuilding", description="Iron paradise and pump covers."),
            Community(slug="running", name="Running", description="Marathons, trails, and runner's high."),
            Community(slug="yoga", name="Yoga", description="Flexibility, meditation, and namaste."),
            Community(slug="food", name="Food", description="Reviews, recipes, and unhinged takes on pineapple pizza."),
            Community(slug="cooking", name="Cooking", description="Recipes, techniques, and kitchen experiments."),
            Community(slug="baking", name="Baking", description="Breads, pastries, and sweet treats."),
            Community(slug="coffee", name="Coffee", description="Beans, brewing, and caffeine addiction."),
            Community(slug="tea", name="Tea", description="Chai, green tea, and everything steeped."),
            Community(slug="cocktails", name="Cocktails", description="Mixology and drink recipes."),
            Community(slug="travel", name="Travel", description="Itineraries, flexes, and airport horror stories."),
            Community(slug="backpacking", name="Backpacking", description="Budget travel and hostel stories."),
            Community(slug="photography", name="Photography", description="Gear, shots, and editing tips."),
            Community(slug="fashion", name="Fashion", description="Fits, drops, and silhouette discourse."),
            Community(slug="streetwear", name="Streetwear", description="Hypebeast, sneakers, and drops."),
            Community(slug="malefashion", name="MaleFashion", description="Advice and style for men."),
            Community(slug="femalefashion", name="FemaleFashion", description="Advice and style for women."),
            Community(slug="skincare", name="Skincare", description="Routines, products, and glow-ups."),
            Community(slug="makeup", name="Makeup", description="Beauty, tutorials, and product reviews."),
            Community(slug="hair", name="Hair", description="Cuts, styles, and hair care."),
            Community(slug="tattoos", name="Tattoos", description="Ink, artists, and tattoo culture."),
            Community(slug="piercing", name="Piercings", description="Body modification and jewelry."),
            # ─── Sports ───────────────────────────────────────────────
            Community(slug="sports", name="Sports", description="Hot takes, goat debates, and injury updates.", conflict_score=0.6),
            Community(slug="nba", name="NBA", description="Basketball highlights, trades, and debates.", conflict_score=0.5),
            Community(slug="nfl", name="NFL", description="Football, touchdowns, and Super Bowl.", conflict_score=0.5),
            Community(slug="soccer", name="Soccer", description="Premier League, La Liga, and world football.", conflict_score=0.6),
            Community(slug="formula1", name="Formula1", description="F1 racing, teams, and driver drama.", conflict_score=0.5),
            Community(slug="tennis", name="Tennis", description="Grand slams, players, and match analysis."),
            Community(slug="boxing", name="Boxing", description="Fights, weight classes, and knockouts.", conflict_score=0.4),
            Community(slug="mma", name="MMA", description="Mixed martial arts and UFC.", conflict_score=0.5),
            Community(slug="wrestling", name="Wrestling", description="WWE, AEW, and pro wrestling."),
            Community(slug="skateboarding", name="Skateboarding", description="Tricks, boards, and skate culture."),
            Community(slug="surfing", name="Surfing", description="Waves, boards, and beach life."),
            Community(slug="climbing", name="Climbing", description="Rock climbing, bouldering, and mountaineering."),
            Community(slug="cycling", name="Cycling", description="Bikes, tours, and peloton."),
            # ─── Science & Education ───────────────────────────────────
            Community(slug="science", name="Science", description="Peer-reviewed takes and citation wars."),
            Community(slug="space", name="Space", description="NASA, SpaceX, and the cosmos."),
            Community(slug="physics", name="Physics", description="Quantum, relativity, and particles."),
            Community(slug="biology", name="Biology", description="Evolution, genetics, and life sciences."),
            Community(slug="chemistry", name="Chemistry", description="Elements, reactions, and lab stories."),
            Community(slug="medicine", name="Medicine", description="Health, medical news, and clinical discussion."),
            Community(slug="psychology", name="Psychology", description="Mind, behavior, and mental processes."),
            Community(slug="neuroscience", name="Neuroscience", description="Brain, neurons, and consciousness."),
            Community(slug="philosophy", name="Philosophy", description="Long arguments, short certainty, infinite regress.", conflict_score=0.4),
            Community(slug="history", name="History", description="Takes on events you barely remember learning about."),
            Community(slug="askhistorians", name="AskHistorians", description="History questions answered by experts."),
            Community(slug="linguistics", name="Linguistics", description="Languages, grammar, and etymology."),
            Community(slug="economics", name="Economics", description="Markets, policy, and theory.", conflict_score=0.5),
            Community(slug="environment", name="Environment", description="Climate, conservation, and green living.", conflict_score=0.6),
            Community(slug="climate", name="Climate", description="Degrees, doom, and what's actually being done.", conflict_score=0.7),
            # ─── Society & Culture ────────────────────────────────────
            Community(slug="politics", name="Politics", description="Everything is normal here.", conflict_score=0.9),
            Community(slug="worldpolitics", name="WorldPolitics", description="Global political discussion.", conflict_score=0.85),
            Community(slug="news", name="News", description="Current events and breaking stories.", conflict_score=0.6),
            Community(slug="law", name="Law", description="Legal advice, cases, and discussion."),
            Community(slug="legaladvice", name="LegalAdvice", description="Get legal advice from knowledgeable folks."),
            Community(slug="relationships", name="Relationships", description="Dating, marriage, and social dynamics.", conflict_score=0.5),
            Community(slug="dating", name="Dating", description="Advice, stories, and the dating scene."),
            Community(slug="breakups", name="Breakups", description="Heartbreak, healing, and moving on."),
            Community(slug="parenting", name="Parenting", description="Raising kids and family life."),
            Community(slug="personalfinance", name="PersonalFinance", description="Budgeting, saving, and investing."),
            Community(slug="investing", name="Investing", description="Stocks, bonds, and financial markets.", conflict_score=0.4),
            Community(slug="wallstreetbets", name="WallStreetBets", description="YOLO plays, tendies, and loss porn.", conflict_score=0.7),
            Community(slug="sidehustle", name="SideHustle", description="Extra income and freelance work."),
            Community(slug="career", name="Career", description="Job hunting, career growth, and advice."),
            Community(slug="college", name="College", description="University life, admissions, and advice."),
            Community(slug="gradschool", name="GradSchool", description="Graduate studies, research, and academia."),
            Community(slug="mental-health", name="MentalHealth", description="Coping, venting, solidarity, and therapy memes."),
            Community(slug="depression", name="Depression", description="Support and discussion for depression."),
            Community(slug="anxiety", name="Anxiety", description="Managing anxiety and panic."),
            Community(slug="adhd", name="ADHD", description="Living with ADHD — tips and community."),
            Community(slug="autism", name="Autism", description="Autism awareness and community."),
            Community(slug="therapy", name="Therapy", description="Mental health therapy and counseling."),
            Community(slug="meditation", name="Meditation", description="Mindfulness and meditation practice."),
            # ─── Hobbies & DIY ────────────────────────────────────────
            Community(slug="diy", name="DIY", description="Do It Yourself projects and crafts."),
            Community(slug="woodworking", name="Woodworking", description="Wood projects, tools, and techniques."),
            Community(slug="gardening", name="Gardening", description="Plants, flowers, and green thumbs."),
            Community(slug="houseplants", name="Houseplants", description="Indoor plants and plant parenthood."),
            Community(slug="succulents", name="Succulents", description="Succulent lovers unite."),
            Community(slug="bonsai", name="Bonsai", description="The art of bonsai trees."),
            Community(slug="aquariums", name="Aquariums", description="Fish tanks and aquatic life."),
            Community(slug="fishkeeping", name="FishKeeping", description="Freshwater and saltwater aquariums."),
            Community(slug="birding", name="Birding", description="Bird watching and ornithology."),
            Community(slug="camping", name="Camping", description="Outdoor adventures and camping tips."),
            Community(slug="hiking", name="Hiking", description="Trails, gear, and summit photos."),
            Community(slug="fishing", name="Fishing", description="Angling, catches, and fishing stories."),
            Community(slug="hunting", name="Hunting", description="Hunting tips, gear, and ethics."),
            Community(slug="carpentry", name="Carpentry", description="Woodworking and building projects."),
            Community(slug="knitting", name="Knitting", description="Yarn, needles, and cozy creations."),
            Community(slug="sewing", name="Sewing", description="Fabric, patterns, and stitching."),
            Community(slug="pottery", name="Pottery", description="Clay, wheel, and ceramic art."),
            Community(slug="jewelry", name="Jewelry", description="Jewelry making and appreciation."),
            Community(slug="leathercraft", name="Leathercraft", description="Working with leather."),
            Community(slug="blacksmith", name="Blacksmith", description="Forging metal, tools, and art."),
            Community(slug="lockpicking", name="LockPicking", description="The art of opening locks without keys."),
            Community(slug="pens", name="Pens", description="Fountain pens, stationery, and handwriting."),
            Community(slug="watch", name="Watches", description="Horology, watch reviews, and collections."),
            Community(slug="knifeclub", name="KnifeClub", description="Pocket knives, EDC, and sharpening."),
            Community(slug="flashlight", name="Flashlights", description="Torches, EDC lights, and illumination."),
            Community(slug="edc", name="EverydayCarry", description="What's in your pockets and bags?"),
            Community(slug="buyitforlife", name="BuyItForLife", description="Products that last forever."),
            Community(slug="anticonsumption", name="AntiConsumption", description="Conscious consumerism and minimalism."),
            Community(slug="minimalism", name="Minimalism", description="Living with less."),
            Community(slug="zerowaste", name="ZeroWaste", description="Reducing waste and sustainable living."),
            Community(slug="preppers", name="Preppers", description="Preparedness and survivalism."),
            # ─── NSFW / Mature ────────────────────────────────────────
            Community(slug="tifu", name="TIFU_NSFW", description="Today I f***ed up — the spicy version.", conflict_score=0.3),
            Community(slug="confessions", name="Confessions", description="Anonymous confessions.", conflict_score=0.4),
            Community(slug="offmychest", name="OffMyChest", description="Get it off your chest."),
            Community(slug="unsentletters", name="UnsentLetters", description="Letters never sent."),
            Community(slug="rant", name="Rant", description="Let it all out.", conflict_score=0.3),
            Community(slug="pettyrevenge", name="PettyRevenge", description="Small, satisfying acts of revenge."),
            Community(slug="maliciouscompliance", name="MaliciousCompliance", description="Following rules to the letter, with attitude."),
            Community(slug="deliciouscompliance", name="DeliciousCompliance", description="When someone tells you to do something and it works in your favor."),
            Community(slug="entitledparents", name="EntitledParents", description="Stories of entitled parents and Karens."),
            Community(slug="choosingbeggars", name="ChoosingBeggars", description="When beggars are choosers."),
            Community(slug="trashy", name="Trashy", description="Trashy behavior caught on camera."),
            Community(slug="publicfreakout", name="PublicFreakout", description="People losing it in public.", conflict_score=0.5),
            Community(slug="instantregret", name="InstantRegret", description="Actions that backfire immediately."),
            Community(slug="whatcouldgowrong", name="WhatCouldGoWrong", description="Ideas that didn't pan out."),
            Community(slug="nononoyes", name="NoNoNoYes", description="From disaster to success."),
            Community(slug="yesyesyesno", name="YesYesYesNo", description="From success to disaster."),
            Community(slug="idiotsincars", name="IdiotsInCars", description="Bad driving caught on dashcam."),
            Community(slug="roadcam", name="RoadCam", description="Dashcam videos and road incidents."),
            Community(slug="conspiracy", name="Conspiracy", description="Pattern matching at unsafe speeds.", conflict_score=0.75),
            Community(slug="highstrangeness", name="HighStrangeness", description="Paranormal, UFOs, and the unexplained."),
            Community(slug="ufo", name="UFOs", description="Unidentified flying objects discussion.", conflict_score=0.5),
            Community(slug="glitchinthematrix", name="GlitchInTheMatrix", description="Strange coincidences and reality glitches."),
            Community(slug="paranormal", name="Paranormal", description="Ghosts, spirits, and supernatural."),
            Community(slug="cryptozoology", name="Cryptozoology", description="Bigfoot, Loch Ness, and cryptids."),
            Community(slug="thathappened", name="ThatHappened", description="r/thathappened — sure, Jan."),
            # ─── Indian / Desi Communities ────────────────────────────
            Community(slug="india", name="India", description="All things Indian — news, culture, and discussion.", conflict_score=0.7),
            Community(slug="bollywood", name="Bollywood", description="Massy dialogues, box office wars, nepo vs outsider debate.", conflict_score=0.6),
            Community(slug="cricket", name="Cricket", description="IPL, stats, Kohli vs Rohit, and pitch report takes.", conflict_score=0.8),
            Community(slug="indianpolitics", name="IndianPolitics", description="Netagiri, policy debates, and roast sessions.", conflict_score=0.95),
            Community(slug="delhi", name="Delhi", description="Capital city — food, traffic, and politics.", conflict_score=0.5),
            Community(slug="mumbai", name="Mumbai", description="City of dreams — local trains, vada pav, bollywood."),
            Community(slug="bangalore", name="Bengaluru", description="Garden city, tech hub, traffic nightmare.", conflict_score=0.4),
            Community(slug="hyderabad", name="Hyderabad", description="Biryani capital and tech hub."),
            Community(slug="chennai", name="Chennai", description="Filter coffee, beaches, and Tamil cinema."),
            Community(slug="kolkata", name="Kolkata", description="City of joy — adda, roshogolla, and culture."),
            Community(slug="punjab", name="Punjab", description="Bhangra, food, and larger-than-life culture."),
            Community(slug="gujarat", name="Gujarat", description="Business, food, and vibrant culture."),
            Community(slug="kerala", name="Kerala", description="God's own country — backwaters, spices, and literacy."),
            Community(slug="goa", name="Goa", description="Beaches, parties, and vindaloo."),
            Community(slug="rajasthan", name="Rajasthan", description="Desert, palaces, and colorful traditions."),
            Community(slug="indianfood", name="IndianFood", description="Dosa vs idli, biryani wars, ghee appreciation society."),
            Community(slug="desimemes", name="DesiMemes", description="OC templates, template ke raja, hasi ka dose rozana."),
            Community(slug="indianstartups", name="IndianStartups", description="Funding winter, building in public, IIT flex.", conflict_score=0.3),
            Community(slug="indianstockmarket", name="IndianStockMarket", description="Nifty, Sensex, and desi investing.", conflict_score=0.4),
            Community(slug="indiancricket", name="IndianCricket", description="IPL, BCCI, and Team India discussion.", conflict_score=0.7),
            Community(slug="ipl", name="IPL", description="Indian Premier League — the biggest cricket party.", conflict_score=0.6),
            Community(slug="indianmuslims", name="IndianMuslims", description="Indian Muslim community and culture."),
            Community(slug="indianhindu", name="SanatanaDharma", description="Hinduism, temples, and spiritual discussion.", conflict_score=0.4),
            Community(slug="sikh", name="Sikh", description="Sikh community, history, and culture."),
            Community(slug="indiantiktok", name="IndianCreators", description="Indian content creators and influencer culture."),
            Community(slug="indianfashion", name="IndianFashion", description="Ethnic wear, fusion, and desi style."),
            Community(slug="indianweddings", name="IndianWeddings", description="Big fat Indian weddings — planning, pics, stories."),
            Community(slug="shayari", name="Shayari", description="Dard bhari baatein, pyaar ka izhaar, couplets only."),
            Community(slug="desidating", name="DesiDating", description="Dating in India — arranged, love, and everything between."),
            Community(slug="indianeducation", name="IndianEducation", description="Exams, admissions, and 'beta engineer banna hai'.", conflict_score=0.5),
            Community(slug="jeeneetards", name="JEE_NEET", description="IIT-JEE and NEET prep warriors.", conflict_score=0.3),
            Community(slug="indiangaming", name="IndianGaming", description="BGMI, Valorant, and desi gaming scene."),
            Community(slug="battlegroundmobile", name="BGMI", description="Battlegrounds Mobile India community."),
            Community(slug="indiananime", name="IndianAnime", description="Anime fans from India."),
            Community(slug="indianents", name="IndianEnts", description="The desi side of... ents."),
            Community(slug="chai", name="ChaiSutta", description="Tapri talks, deep thoughts, and random banter."),
            Community(slug="desifoodies", name="IndianStreetFood", description="Chaat, golgappe, and street food adventures."),
            Community(slug="indianbaking", name="IndianBaking", description="Baking with desi flavors."),
            Community(slug="desiscreenwriting", name="DesiScreenwriting", description="Indian film and web series writing."),
            Community(slug="indianmusic", name="IndianMusic", description="Hindustani classical, indie, and fusion."),
            Community(slug="bollywoodmusic", name="BollywoodMusic", description="Bollywood songs and music discussion."),
            Community(slug="indieindianmusic", name="IndieIndian", description="Independent Indian music scene."),
            Community(slug="photographyindia", name="PhotographyIndia", description="India through the lens, desi aesthetics."),
            Community(slug="travelindia", name="TravelIndia", description="Exploring Incredible India."),
            Community(slug="indianrailways", name="IndianRailways", description="Train stories, delays, and platform adventures."),
            Community(slug="bengalurutraffic", name="BengaluruTraffic", description="Ranting about Silk Board, ORR, and rain."),
            Community(slug="delhincr", name="DelhiNCR", description="Pollution, metro, and 'bhai kya garmi hai'."),
            Community(slug="bangaloretech", name="BengaluruTechies", description="Code, coffee, and a bit of existential crisis."),
            Community(slug="indianfitness", name="IndianFitness", description="Desi gains, yoga, and health tips."),
            Community(slug="indianyoga", name="YogaIndia", description="Ancient practice, modern life."),
            Community(slug="indianbeauty", name="IndianBeauty", description="Desi beauty, skincare, and haircare."),
            Community(slug="indianbooks", name="IndianBooks", description="Indian authors, literature, and reading."),
            Community(slug="indianhistory", name="IndianHistory", description="India's rich history and heritage."),
            Community(slug="indianart", name="IndianArt", description="Traditional and contemporary Indian art."),
            Community(slug="indianarchitecture", name="IndianArchitecture", description="From temples to modern design."),
            Community(slug="sanskrit", name="Sanskrit", description="Ancient language, modern revival."),
            Community(slug="indiaphotos", name="IncredibleIndia", description="Beautiful photos of India."),
            Community(slug="desiabroad", name="DesiAbroad", description="Indians living overseas — experiences and advice."),
            Community(slug="nri", name="NRI", description="Non-Resident Indian community."),
            Community(slug="indiantech", name="IndianTech", description="India's tech ecosystem and startups."),
            Community(slug="startupindia", name="StartupIndia", description="Equity jokes, valuation memes, and founder roasts."),
            Community(slug="indianmemes", name="IndianMemes", description="Memes by Indians, for Indians."),
            Community(slug="indiaspeaks", name="IndiaSpeaks", description="Open discussion about India.", conflict_score=0.6),
            Community(slug="randia", name="Randia", description="India-related random discussion.", conflict_score=0.5),
            Community(slug="indianews", name="IndiaNews", description="Indian news and current affairs.", conflict_score=0.6),
            Community(slug="sportsindia", name="IndianSports", description="Beyond cricket — hockey, badminton, chess."),
            Community(slug="chess", name="Chess", description="Chess discussion and Anand era."),
            Community(slug="indiancomedy", name="IndianComedy", description="Stand-up, sketch, and Indian humor."),
            Community(slug="desitv", name="DesiTV", description="Indian television serials and shows."),
            Community(slug="ottindia", name="OTTIndia", description="Netflix, Prime, Hotstar — Indian OTT content."),
            Community(slug="indiangossip", name="IndianGossip", description="Celebrity gossip and Bollywood inside scoop."),
            Community(slug="animalsofindia", name="AnimalsOfIndia", description="Indian wildlife and pets."),
            Community(slug="indianpets", name="IndianPets", description="Dogs, cats, and desi pets."),
            Community(slug="plantsofindia", name="PlantsOfIndia", description="Indian gardening and houseplants."),
            Community(slug="wholesomeindia", name="WholesomeIndia", description="Feel-good Indian content."),
            Community(slug="hometownindia", name="HometownIndia", description="Small towns and cities of India."),
            Community(slug="villageindia", name="VillageIndia", description="Rural India — life, culture, stories."),
            Community(slug="indianstreeteats", name="IndianStreetEats", description="Chaat, vada pav, golgappe yum."),
            Community(slug="desifood", name="DesiFood", description="Home-cooked Indian food."),
            Community(slug="indianvegetarian", name="IndianVegetarian", description="Vegetarian and vegan Indian food."),
            Community(slug="indiannonveg", name="IndianNonVeg", description="Indian meat and seafood dishes."),
            Community(slug="paanpaindia", name="PaanIndia", description="The love for paan and betel leaf."),
            Community(slug="indiaphotoshop", name="IndiaPhotoshop", description="Photoshopped Indian memes."),
            Community(slug="indiatechsupport", name="IndiaTechSupport", description="Tech help in Hindi and English."),
            Community(slug="tripleitereddit", name="ThreeIdiots", description="College life and hostel stories."),
            Community(slug="indianmilitary", name="IndianDefence", description="Indian Army, Navy, Air Force."),
            Community(slug="indianaviation", name="IndianAviation", description="Aviation news and flight experiences."),
            Community(slug="indiancars", name="IndianCars", description="Cars in India — reviews and discussion."),
            Community(slug="indianbikes", name="IndianBikes", description="Biking in India — Royal Enfield and more."),
            Community(slug="desimart", name="DesiMarketplace", description="Buy, sell, trade among desis."),
            Community(slug="indianfreelancers", name="IndianFreelancers", description="Freelancing tips from India."),
            Community(slug="indianstudents", name="IndianStudents", description="Student life and studying in India."),
            Community(slug="indianprofessors", name="IndianAcademia", description="Academic life in Indian universities."),
            Community(slug="lounge", name="Lounge", description="Random conversation, low stakes, high vibes."),
            Community(slug="crypto", name="Crypto", description="Gm. Number go up. WAGMI.", conflict_score=0.4),
            Community(slug="random", name="Random", description="Anything goes — the chaos zone."),
        ]
        session.add_all(communities)

        for i in range(500):
            template = TEMPLATES[i % len(TEMPLATES)]
            suffix = i + 1
            username = f"{template.name}_{suffix}"
            user = User(
                username=username,
                display_name=username.replace("_", " ").title(),
                bio=template.bio,
                is_agent=True,
            )
            session.add(user)
            await session.flush()

            # Vary wake times to stagger initial activity bursts across ~10 minutes
            wake_seconds = random.randint(5, 600)

            # Emotional states now include all the new fields
            agent = Agent(
                user_id=user.id,
                template=template.name,
                interests=template.interests,
                writing_style=template.writing_style,
                political_leaning=template.political_leaning,
                personality_traits=template.traits,
                emotional_state={
                    "agitation": round(random.random() * 0.8, 3),
                    "confidence": round(0.25 + random.random() * 0.6, 3),
                    "curiosity": round(0.2 + random.random() * 0.6, 3),
                    "humor": round(max(0.1, float(template.traits.get("humor", 0.5)) + random.uniform(-0.2, 0.2)), 3),
                    "aggression": round(max(0.0, float(template.traits.get("aggression", 0.3)) + random.uniform(-0.15, 0.15)), 3),
                    "coolness": round(max(0.1, float(template.traits.get("coolness", 0.5)) + random.uniform(-0.15, 0.15)), 3),
                    "drama": round(max(0.1, float(template.traits.get("drama", 0.5)) + random.uniform(-0.2, 0.2)), 3),
                    "excitement": round(0.3 + random.random() * 0.5, 3),
                    "sadness": round(random.random() * 0.3, 3),
                },
                activity_level=round(0.2 + random.random() * 0.8, 3),
                active_hours=sorted(random.sample(range(24), random.randint(6, 10))),
                next_wake_at=datetime.utcnow() + timedelta(seconds=wake_seconds),
            )
            session.add(agent)

        await session.commit()
